
import '../movie.dart';
import '../services/base_service.dart';
import '../services/popular_service.dart';

class PopularRepository {
  BaseService _popularService = PopularService();

  Future<List> fetchMovies() async {
    dynamic response = await _popularService.getResponse('/popular');

    final jsonData = response['results'] as List;

    List articles = jsonData.map((e) => Autogenerated.fromJson(e)).toList();
    return articles;
  }
}
