import 'package:flutter/cupertino.dart';

import '../core/api_response.dart';
import '../model/movie.dart';
import '../model/repositories/popular_repository.dart';

class MoviesListViewModel extends ChangeNotifier {
  ApiResponse _apiResponse = ApiResponse.initial('Empty');

  ApiResponse get response {
    return _apiResponse;
  }

  List<Autogenerated> articles = [];

  List<Autogenerated> get movies {
    return articles;
  }

  Future<void> fetchPopularMovies() async {
    try {
      List articles = await PopularRepository().fetchMovies();
      articles = articles;
      _apiResponse = ApiResponse.completed(articles);
    } catch (e) {
      _apiResponse = ApiResponse.error(e.toString());
    }
    notifyListeners();
  }
}
