import 'dart:math';

import 'package:bloc/bloc.dart';
import 'package:equatable/equatable.dart';
import 'package:meta/meta.dart';

import '../data/repository/news_repo.dart';
import '../model/movie.dart';

part 'news_event.dart';

part 'news_state.dart';

class NewsBloc extends Bloc<NewsEvent, NewsState> {
  NewsRepository newsRepository;

  NewsBloc(this.newsRepository) : super(NewsInitialState()) {
    on((event, emit) async {
      try {
        List<Autogenerated> articles = await newsRepository.getNews();
        emit(NewsLoadedState(articles));
      } catch (e) {
        emit(NewsErrorState(e.toString()));
      }
    });
  }
}
